// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "drsg:preprocess@1.0.0".

//go:wasmimport drsg:preprocess/host@1.0.0 list
//go:noescape
func wasmimport_List(suffix0 *uint8, suffix1 uint32, result *cm.Result[cm.List[string], cm.List[string], string])

//go:wasmimport drsg:preprocess/host@1.0.0 read
//go:noescape
func wasmimport_Read(path0 *uint8, path1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], string])

//go:wasmimport drsg:preprocess/host@1.0.0 label
//go:noescape
func wasmimport_Label(result *cm.Option[string])
