// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "drsg:preprocess/host@1.0.0".
//
// What the host will answer. This *is* the capability grant: a plugin can
// reach exactly what is written here and nothing else — no filesystem, no
// network, no environment, and no way to write anything anywhere.
//
// Input arrives by **pull, not push**: a repository copied into linear memory
// would be both a needless copy and a 4 GiB ceiling, and pulling is what lets
// a code plugin follow an import across files.
package host

import (
	"go.bytecodealliance.org/cm"
)

// List represents the imported function "list".
//
// `%list` escapes the keyword: the function keeps the name the host's own
// trait uses, rather than the two drifting apart over a lexical accident.
// Readable paths whose name ends with `suffix` ("" for all), relative to
// the root, **sorted**.
//
// Sorted is part of the contract rather than a convenience: unsorted
// directory order would vary fact and prose order between runs, and
// re-ingesting a repository is meant to yield the same graph.
//
//	%list: func(suffix: string) -> result<list<string>, string>
//
//go:nosplit
func List(suffix string) (result cm.Result[cm.List[string], cm.List[string], string]) {
	suffix0, suffix1 := cm.LowerString(suffix)
	wasmimport_List((*uint8)(suffix0), (uint32)(suffix1), &result)
	return
}

// Read represents the imported function "read".
//
// One file's bytes. A path outside the root the host was given is
// refused — the check is on the resolved path, so `..` and symlinks do
// not walk through it.
//
//	read: func(path: string) -> result<list<u8>, string>
//
//go:nosplit
func Read(path string) (result cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	path0, path1 := cm.LowerString(path)
	wasmimport_Read((*uint8)(path0), (uint32)(path1), &result)
	return
}

// Label represents the imported function "label".
//
// What to call the thing being read, when its contents do not say.
// A Rust crate normally names itself in its manifest, but pointed at a
// bare `src/` directory there is no manifest to read.
//
//	label: func() -> option<string>
//
//go:nosplit
func Label() (result cm.Option[string]) {
	wasmimport_Label(&result)
	return
}
