// Code generated by wit-bindgen-go. DO NOT EDIT.

package preprocessor

import (
	"go.bytecodealliance.org/cm"
	"strconv"
	"unsafe"
)

// DocShape is used for storage in variant or result types.
type DocShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Doc{})]byte
}

func lift_Doc(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) (v Doc) {
	v.Name = cm.LiftString[string](f0, f1)
	v.Bytes = cm.LiftList[cm.List[uint8]](f2, f3)
	return
}

func lift_Input(f0 uint32, f1 uint32, f2 uint32, f3 *uint8, f4 uint32) (v Input) {
	switch f0 {
	case 0:
		return cm.New[Input](0, lift_Doc(cm.U32ToPointer[uint8](f1), (uint32)(f2), (*uint8)(f3), (uint32)(f4)))
	case 1:
		return cm.New[Input](1, cm.LiftList[cm.List[string]](cm.U32ToPointer[string](f1), (uint32)(f2)))
	}
	panic("lift variant: unknown case: " + strconv.Itoa(int(f0)))
}

// OutputShape is used for storage in variant or result types.
type OutputShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Output{})]byte
}
