// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package preprocessor represents the exported interface "drsg:preprocess/preprocessor@1.0.0".
//
// What a plugin must provide.
package preprocessor

import (
	"go.bytecodealliance.org/cm"
)

// Manifest represents the record "drsg:preprocess/preprocessor@1.0.0#manifest".
//
// What the plugin is and what it claims.
//
//	record manifest {
//		name: string,
//		version: string,
//		extensions: list<string>,
//	}
type Manifest struct {
	_ cm.HostLayout `json:"-"`
	// Lowercase, stable: it is half of `_generated_by` and the name an
	// operator passes to `--handler`.
	Name string `json:"name"`

	// The other half of `_generated_by`. They are never useful apart.
	Version string `json:"version"`

	// Extensions this handles, lowercase and without the dot.
	Extensions cm.List[string] `json:"extensions"`
}

// Doc represents the record "drsg:preprocess/preprocessor@1.0.0#doc".
//
// A single document — an upload, a fetched body, one file.
//
//	record doc {
//		name: string,
//		bytes: list<u8>,
//	}
type Doc struct {
	_     cm.HostLayout  `json:"-"`
	Name  string         `json:"name"`
	Bytes cm.List[uint8] `json:"bytes"`
}

// Input represents the variant "drsg:preprocess/preprocessor@1.0.0#input".
//
// One unit of work for `parse`. `files` carries one chunk of the paths
// the router assigned to this plugin; the plugin may still pull more
// through the host, which is where a cross-file call graph comes from.
//
//	variant input {
//		document(doc),
//		files(list<string>),
//	}
type Input cm.Variant[uint8, DocShape, Doc]

// InputDocument returns a [Input] of case "document".
func InputDocument(data Doc) Input {
	return cm.New[Input](0, data)
}

// Document returns a non-nil *[Doc] if [Input] represents the variant case "document".
func (self *Input) Document() *Doc {
	return cm.Case[Doc](self, 0)
}

// InputFiles returns a [Input] of case "files".
func InputFiles(data cm.List[string]) Input {
	return cm.New[Input](1, data)
}

// Files returns a non-nil *[cm.List[string]] if [Input] represents the variant case "files".
func (self *Input) Files() *cm.List[string] {
	return cm.Case[cm.List[string]](self, 1)
}

var _InputStrings = [2]string{
	"document",
	"files",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Input) String() string {
	return _InputStrings[v.Tag()]
}

// Node represents the record "drsg:preprocess/preprocessor@1.0.0#node".
//
// A fact about a thing.
//
// `properties` is a **JSON object**. WIT has no recursive types and a
// property value may itself be a list or a map of values, so the shape
// travels as JSON — which is also exactly what `digest.write` accepts, so
// this reuses a path that already exists rather than inventing a
// flattening for the occasion.
//
//	record node {
//		key: string,
//		label: string,
//		extra-labels: list<string>,
//		properties: string,
//	}
type Node struct {
	_   cm.HostLayout `json:"-"`
	Key string        `json:"key"`

	// The kind of thing this is, in the plugin's own vocabulary.
	Label string `json:"label"`

	// Further labels asserted rather than chosen — `External` on a node
	// standing in for something outside the tree that was read. They take
	// no part in the model's label reconciliation.
	ExtraLabels cm.List[string] `json:"extra-labels"`
	Properties  string          `json:"properties"`
}

// Edge represents the record "drsg:preprocess/preprocessor@1.0.0#edge".
//
// A fact about a relation. `src` and `dst` are node keys.
//
//	record edge {
//		src: string,
//		dst: string,
//		%type: string,
//		properties: string,
//	}
type Edge struct {
	_          cm.HostLayout `json:"-"`
	Src        string        `json:"src"`
	Dst        string        `json:"dst"`
	Type       string        `json:"type"`
	Properties string        `json:"properties"`
}

// Report represents the record "drsg:preprocess/preprocessor@1.0.0#report".
//
// What ran, and what it could not do.
//
// Counted and named rather than dropped silently: a thin graph should be
// explained by its report, not investigated by re-running the ingest with
// different arguments.
//
//	record report {
//		facts: u32,
//		prose-chars: u32,
//		skipped: u32,
//		notes: list<string>,
//	}
type Report struct {
	_          cm.HostLayout `json:"-"`
	Facts      uint32        `json:"facts"`
	ProseChars uint32        `json:"prose-chars"`

	// Inputs this plugin could not read, or that held nothing.
	Skipped uint32 `json:"skipped"`

	// Anything a reader would want said in words — what could not be
	// resolved, and why.
	Notes cm.List[string] `json:"notes"`
}

// Output represents the record "drsg:preprocess/preprocessor@1.0.0#output".
//
// Facts, prose, and an account of both.
//
//	record output {
//		nodes: list<node>,
//		edges: list<edge>,
//		prose: string,
//		report: report,
//	}
type Output struct {
	_     cm.HostLayout `json:"-"`
	Nodes cm.List[Node] `json:"nodes"`
	Edges cm.List[Edge] `json:"edges"`

	// Empty means no model call is needed at all.
	Prose  string `json:"prose"`
	Report Report `json:"report"`
}
