// Code generated by wit-bindgen-go. DO NOT EDIT.

package preprocessor

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "drsg:preprocess/preprocessor@1.0.0".
var Exports struct {
	// Describe represents the caller-defined, exported function "describe".
	//
	// Called once when the plugin is installed and again before it is used,
	// so a registry entry that has drifted from the artifact is caught rather
	// than trusted.
	//
	//	describe: func() -> manifest
	Describe func() (result Manifest)

	// Parse represents the caller-defined, exported function "parse".
	//
	// Phase one: one chunk of the input becomes a **partial**.
	//
	// The partial is opaque to the host — serialize whatever your `assemble`
	// wants to read; the host shuttles the bytes and never looks inside.
	// Called once per chunk, possibly concurrently in separate instances that
	// share nothing, so `parse` must depend only on its input and the host.
	//
	// `options` are this plugin's own settings, from `[plugins.<name>]` in
	// the operator's config — passed through uninterpreted, because what a
	// plugin can be configured to do is the plugin's business.
	//
	//	parse: func(subject: input, options: list<tuple<string, string>>) -> result<list<u8>,
	//	string>
	Parse func(subject Input, options cm.List[[2]string]) (result cm.Result[cm.List[uint8], cm.List[uint8], string])

	// Assemble represents the caller-defined, exported function "assemble".
	//
	// Phase two: every partial, **in chunk order**, becomes the result.
	//
	// Called exactly once per run. This is where cross-file resolution lives —
	// and it lives *here*, in the plugin, because it is language semantics and
	// the database refuses to hold any. The result must not depend on where
	// the chunk boundaries fell.
	//
	//	assemble: func(partials: list<list<u8>>, options: list<tuple<string, string>>)
	//	-> result<output, string>
	Assemble func(partials cm.List[cm.List[uint8]], options cm.List[[2]string]) (result cm.Result[OutputShape, Output, string])
}
