// Code generated by wit-bindgen-go. DO NOT EDIT.

package preprocessor

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "drsg:preprocess@1.0.0".

//go:wasmexport drsg:preprocess/preprocessor@1.0.0#describe
//export drsg:preprocess/preprocessor@1.0.0#describe
func wasmexport_Describe() (result *Manifest) {
	result_ := Exports.Describe()
	result = &result_
	return
}

//go:wasmexport drsg:preprocess/preprocessor@1.0.0#parse
//export drsg:preprocess/preprocessor@1.0.0#parse
func wasmexport_Parse(subject0 uint32, subject1 uint32, subject2 uint32, subject3 *uint8, subject4 uint32, options0 *[2]string, options1 uint32) (result *cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	subject := lift_Input((uint32)(subject0), (uint32)(subject1), (uint32)(subject2), (*uint8)(subject3), (uint32)(subject4))
	options := cm.LiftList[cm.List[[2]string]]((*[2]string)(options0), (uint32)(options1))
	result_ := Exports.Parse(subject, options)
	result = &result_
	return
}

//go:wasmexport drsg:preprocess/preprocessor@1.0.0#assemble
//export drsg:preprocess/preprocessor@1.0.0#assemble
func wasmexport_Assemble(partials0 *cm.List[uint8], partials1 uint32, options0 *[2]string, options1 uint32) (result *cm.Result[OutputShape, Output, string]) {
	partials := cm.LiftList[cm.List[cm.List[uint8]]]((*cm.List[uint8])(partials0), (uint32)(partials1))
	options := cm.LiftList[cm.List[[2]string]]((*[2]string)(options0), (uint32)(options1))
	result_ := Exports.Assemble(partials, options)
	result = &result_
	return
}
